version: '3.9'
services:
  backend:
    build:
      context: ./pazaryeri-backend/
      dockerfile: Dockerfile
    networks:
      - pazaryeri-network
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pazaryeri-network
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.2-alpine
    networks:
      - pazaryeri-network
volumes:
  db-data:
networks:
  pazaryeri-network:
